# Build the pages documentation

name: build-deployer-doc

# Trigger the workflow on push or pull request events but only for the main branch
on:
  push:
    branches:
    - main
    paths:
    - 'docs/**'
  pull_request:
    branches:
    - main
    paths:
    - 'doc/**'


  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Sequence of tasks that will be executed as part of the job
    steps:

      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Build the static pages
        run: |
          make venv
          make build
        working-directory: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Deploy static pages to gh-pages branch
        if: ${{ github.event_name == 'push' }}
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          make deploy
        working-directory: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}